// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace htmlvisibleonly.RecordedUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class RecordedUIMap
    {
        
        /// <summary>
        /// ClickHello
        /// </summary>
        public void ClickHello()
        {
            #region Variable Declarations
            HtmlHyperlink uIHelloHyperlink = this.UIItem2ad6de5575f1403fWindow.UIItem2ad6de5575f1403fDocument.UIHelloHyperlink;
            #endregion

            // Click 'Hello' link
            Mouse.Click(uIHelloHyperlink, new Point(53, 20));
        }
        
        #region Properties
        public UIItem2ad6de5575f1403fWindow UIItem2ad6de5575f1403fWindow
        {
            get
            {
                if ((this.mUIItem2ad6de5575f1403fWindow == null))
                {
                    this.mUIItem2ad6de5575f1403fWindow = new UIItem2ad6de5575f1403fWindow();
                }
                return this.mUIItem2ad6de5575f1403fWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItem2ad6de5575f1403fWindow mUIItem2ad6de5575f1403fWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItem2ad6de5575f1403fWindow : BrowserWindow
    {
        
        public UIItem2ad6de5575f1403fWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "2ad6de55-75f1-403f-8fcb-1d5defac9786";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("2ad6de55-75f1-403f-8fcb-1d5defac9786");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIItem2ad6de5575f1403fDocument UIItem2ad6de5575f1403fDocument
        {
            get
            {
                if ((this.mUIItem2ad6de5575f1403fDocument == null))
                {
                    this.mUIItem2ad6de5575f1403fDocument = new UIItem2ad6de5575f1403fDocument(this);
                }
                return this.mUIItem2ad6de5575f1403fDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIItem2ad6de5575f1403fDocument mUIItem2ad6de5575f1403fDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItem2ad6de5575f1403fDocument : HtmlDocument
    {
        
        public UIItem2ad6de5575f1403fDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "2ad6de55-75f1-403f-8fcb-1d5defac9786";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "D:/jason/dev/CodedUIHtmlVisibleOnlyIssue/htmlvisibleonly/example2.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "file://D:\\jason\\dev\\CodedUIHtmlVisibleOnlyIssue\\htmlvisibleonly\\example2.htm";
            this.WindowTitles.Add("2ad6de55-75f1-403f-8fcb-1d5defac9786");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHelloHyperlink
        {
            get
            {
                if ((this.mUIHelloHyperlink == null))
                {
                    this.mUIHelloHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHelloHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHelloHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHelloHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHelloHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Hello";
                    this.mUIHelloHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "D:/jason/dev/CodedUIHtmlVisibleOnlyIssue/htmlvisibleonly/example2.htm";
                    this.mUIHelloHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHelloHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "file:///D:/jason/dev/CodedUIHtmlVisibleOnlyIssue/htmlvisibleonly/example2.htm#";
                    this.mUIHelloHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHelloHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"#\"";
                    this.mUIHelloHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIHelloHyperlink.WindowTitles.Add("2ad6de55-75f1-403f-8fcb-1d5defac9786");
                    #endregion
                }
                return this.mUIHelloHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHelloHyperlink;
        #endregion
    }
}
